// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFY15uyFXMRnC2y9uhVR_JNp9dvECyAoo',
    appId: '1:431243640261:web:d4b818466cb10c3293dfac',
    messagingSenderId: '431243640261',
    projectId: 'voicesewa',
    authDomain: 'voicesewa.firebaseapp.com',
    storageBucket: 'voicesewa.firebasestorage.app',
    measurementId: 'G-YHCWT244PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa2I-7TTJ96aHU-Ab7wvdKy79hJbnkD9s',
    appId: '1:431243640261:android:147e3d236f85e74893dfac',
    messagingSenderId: '431243640261',
    projectId: 'voicesewa',
    storageBucket: 'voicesewa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjWIObUNj7w_j28aTwUE5Q4HokKXt-igE',
    appId: '1:431243640261:ios:1cbff4f8cb5422aa93dfac',
    messagingSenderId: '431243640261',
    projectId: 'voicesewa',
    storageBucket: 'voicesewa.firebasestorage.app',
    iosBundleId: 'com.example.voicesewaWorker',
  );
}
